changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Maintenance
      labels:
        - ci
        - chore
        - refactor
        - docs
    - title: Other Changes
      labels:
        - "*"
